name: expanse_management
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.7

  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^31.1.21
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  syncfusion_flutter_datepicker: ^31.1.21
  table_calendar: ^3.0.9
  intl: ^0.20.2
  
  # Notification packages
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  shared_preferences: ^2.2.3

  # Ép version win32 xuống để tránh lỗi UnmodifiableUint8ListView
  win32: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
